### ISSUE TITLE
er staan temp-files in je repository

### ISSUE THREAD

**Issue by stgm** [Alixdo/chocofair#1]
sluit je documenten voordat je ze commit (hoeft niet bij code, hiervoor worden geen tempfiles gemaakt). zorg dat je de tempfiles weer uit je repo verwijdert.

**Comment by Alixdo** [comment]
Ik heb ze gedelete. Dit gaat waarschijnlijk weer gebeuren. Ik start namenlijk op van CD (live session) en push is mijn enige manier om echt op te slaan.
